# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build-Test-Deploy Pipeline

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Server - run build
      run: |
        cd server
        npm ci
        npm run build --if-present

    - name: UI - run build
      run: |
        cd ui
        npm ci
        npm run build --if-present

    - uses: actions/upload-artifact@master
      with:
        name: build
        path: |
          ui/dist
          server

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/download-artifact@master
      with:
        name: build
        path: |
          ui/dist
          server
    - name: Server - run tests    
      run: |
        cd server
        npm test

    - name: UI - run tests    
      run: |
        cd ui
        npm test

  coverage:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Code Coverage
      if: >- 
        github.event_name == 'pull_request'
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./server/coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [coverage]

    steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: ./ui/dist/
